export enum GROUPS {
  FEMENINO = 'FEMENINO',
  ENTRENAMIENTO = 'ENTRENAMIENTO',
  PEQUES = 'PEQUES',
  PRIMERCICLO = 'PRIMER_CICLO',
  SEGUNDOCICLO = 'SEGUNDO_CICLO',
  SECUNDARIA = 'SECUNDARIA',
  QUINTA = 'QUINTA',
  SEXTA = 'SEXTA',
  SEPTIMA = 'SEPTIMA',
  OCTAVA = 'OCTAVA',
  NOVENA = 'NOVENA',
}
